version: '4.4'

services:
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-user}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DB_NAME:-advs_database}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb

  advs:
    build: .
    ports:
      - 80:3000
    environment:
      - SERVER_PORT=${SERVER_PORT:-7070}
      - DB_USERNAME=${DB_USERNAME:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-advs_database}
      - DB_HOST=mongodb://mongodb:27017
      - COOKIE_SECRET=${COOKIE_SECRET:-password}
    depends_on:
      - mongodb